### ISSUE TITLE
Unable to quantize network which includes Normalization layer

### ISSUE THREAD

**Issue by uu-praveeng** [ARM-software/armnn#347]
Hi ,

I have created a sample network which includes Normalization Layer. I was able to do the FP32 inference but unable to create a quantized armnn model . Below is the error which that I faced during the quantization.

```
terminate called after throwing an instance of 'armnn::Exception'
  what():  Have no entry for layer GUID [6]

Program received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff57e642a in __GI_abort () at abort.c:89
#2  0x00007ffff60fd0ad in __gnu_cxx::__verbose_terminate_handler() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007ffff60fb066 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff60fb0b1 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff60fb2c9 in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007ffff71fa1e6 in armnn::RangeTracker::GetRange (this=0x55555579eb50, guid=..., idx=0) at /local-ssd/pgajula/Project/DeepLearning/ARM/Intel1911/armnn/src/armnn/RangeTracker.cpp:36
#7  0x00007ffff71ee3d7 in armnn::QuantizerVisitor::CreateQuantizedBias (this=0x7fffffffd5a0, srcLayer=0x555555799980, weights=..., biases=..., backing=...)
    at /local-ssd/pgajula/Project/DeepLearning/ARM/Intel1911/armnn/src/armnn/QuantizerVisitor.cpp:90
#8  0x00007ffff71eedfc in armnn::QuantizerVisitor::VisitConvolution2dLayer (this=0x7fffffffd5a0, layer=0x555555799980, convolution2dDescriptor=..., weights=..., biases=..., name=0x5555557999b0 "convLayer")
    at /local-ssd/pgajula/Project/DeepLearning/ARM/Intel1911/armnn/src/armnn/QuantizerVisitor.cpp:230
#9  0x00007ffff7111ba5 in armnn::Convolution2dLayer::Accept (this=0x555555799980, visitor=...) at /local-ssd/pgajula/Project/DeepLearning/ARM/Intel1911/armnn/src/armnn/layers/Convolution2dLayer.cpp:147
#10 0x00007ffff71d18b3 in armnn::VisitLayers<armnn::Graph> (layerContainer=..., visitor=...) at /local-ssd/pgajula/Project/DeepLearning/ARM/Intel1911/armnn/src/armnn/NetworkQuantizerUtils.hpp:59
#11 0x00007ffff71cfb95 in armnn::NetworkQuantizer::ExportNetwork (this=0x55555579eaa0) at /local-ssd/pgajula/Project/DeepLearning/ARM/Intel1911/armnn/src/armnn/NetworkQuantizer.cpp:175
#12 0x00005555555664ef in main (argc=10, argv=0x7fffffffe128) at /local-ssd/pgajula/Project/DeepLearning/ARM/Intel1911/armnn/src/armnnQuantizer/ArmNNQuantizerMain.cpp:117

```

Could you look into this issue.
I have attached the below files for your reference:
1. GoogleNet.cpp - for FP32 inference and armnn model creation
2. img.txt for FP32 inference
3. img.raw , csv file used for quantization
4. FP32 models

[GoogleNet.zip](https://github.com/ARM-software/armnn/files/4235602/GoogleNet.zip)

Thank you,
Praveen.

**Comment by morgolock** [comment]
Hi @uu-praveeng 

Could you please let us know the following:

1. armnn version your are working on
2. the command you type when you run the tool

**Comment by morgolock** [comment]
Hi @uu-praveeng 

We're working on a patch to fix this problem, in the meantime you could use the solution shown below:

```
diff --git a/src/armnn/DynamicQuantizationVisitor.cpp b/src/armnn/DynamicQuantizationVisitor.cpp
index 4b1dce0b..c8100bc2 100644
--- a/src/armnn/DynamicQuantizationVisitor.cpp
+++ b/src/armnn/DynamicQuantizationVisitor.cpp
@@ -108,6 +108,16 @@ void DynamicQuantizationVisitor::VisitBatchNormalizationLayer(const IConnectable
     AddToCalibratedLayers(layer);
 }
 
+void DynamicQuantizationVisitor::VisitNormalizationLayer(const IConnectableLayer* layer,
+                                 const NormalizationDescriptor& desc,
+                                 const char* name)
+{
+    boost::ignore_unused(desc);
+    boost::ignore_unused(name);
+    SetRange(layer, 0, -15.0f, 15.0f);
+    AddToCalibratedLayers(layer);
+}
+
 void DynamicQuantizationVisitor::VisitConvolution2dLayer(const IConnectableLayer* layer,
                                                          const Convolution2dDescriptor& convolution2dDescriptor,
                                                          const ConstTensor& weights,
diff --git a/src/armnn/DynamicQuantizationVisitor.hpp b/src/armnn/DynamicQuantizationVisitor.hpp
index 43768fd0..16f826eb 100644
--- a/src/armnn/DynamicQuantizationVisitor.hpp
+++ b/src/armnn/DynamicQuantizationVisitor.hpp
@@ -25,6 +25,10 @@ public:
     /// Functions to set the Range on a per-layer-type basis
     void VisitAdditionLayer(const IConnectableLayer* layer, const char* name = nullptr) override;
 
+    void VisitNormalizationLayer(const IConnectableLayer* layer,
+                                 const NormalizationDescriptor& desc,
+                                 const char* name = nullptr) override ;
+
     void VisitBatchNormalizationLayer(const IConnectableLayer* layer,
                                       const BatchNormalizationDescriptor& desc,
                                       const ConstTensor& mean,
@@ -134,4 +138,4 @@ private:
     void RemoveDebugLayers();
 };
 
-} //namespace armnn
\ No newline at end of file
+} //namespace armnn
```

Hope this helps.

**Comment by uu-praveeng** [comment]
Hi @morgolock ,

Thanks for the patch. I was able to do the quantization now and inference as well.
I found huge difference wrt FP32 output vs INT8 output. 
Could you cross verify the same and let me know how you fare.

Thank you,
Praveen.

**Comment by uu-praveeng** [comment]
Hi @morgolock 

Any update on this. Let me know if you need any inputs.

Thank you,
Praveen

**Comment by morgolock** [comment]
Hi @uu-praveeng 

Could you please provide some numbers showing the differences you mentioned?

ArmNN quantisation is experimental, I'd suggest using tensorflow quantisation tools instead.

**Comment by FrancisMurtagh-arm** [comment]
Closing due to inactivity.
