### ISSUE TITLE
Problems with building Pyarmnn and Onnx, TFparsers

### ISSUE THREAD

**Issue by psk9211** [ARM-software/armnn#544]
Hi.

I'm planning to use Arm Compute Library and ArmNN as EP of ONNXruntime, and compare onnx model inference performances under several conditions using pyarmnn and onnxruntime on RPI4.

I just built ArmNN 21.02 on my Raspberry pi 4 ([64-bit OS](https://downloads.raspberrypi.org/raspios_lite_arm64/images/raspios_lite_arm64-2021-04-09/)) using this [doc](https://arm-software.github.io/armnn/21.02/md__build_guide_cross_compilation.xhtml) (without OpenCL Caffe), and passed the UnitTests.

-   x86_x64 machine
    -   Ubuntu 18.04.1 on Docker
    -   python 3.8.3, conda env
-   RPI 4
    -   aarch64 (5.10.17-v8+ kernel)
    -   python 3.7.3

```bash
pi@raspberrypi:~/armnn/build$ ./UnitTests --run_test=\!DynamicBackendTests
Running 3610 test cases...

*** No errors detected
```

```bash
CXX=aarch64-linux-gnu-g++ CC=aarch64-linux-gnu-gcc cmake .. \
        -DCMAKE_C_COMPILER_FLAGS=-fPIC \
        -DARMCOMPUTE_ROOT=$HOME/armnn-devenv/ComputeLibrary \
        -DARMCOMPUTE_BUILD_DIR=$HOME/armnn-devenv/ComputeLibrary/build/ \
        -DBOOST_ROOT=$HOME/armnn-devenv/boost_arm64_install/ \
        -DARMCOMPUTENEON=1 -DARMNNREF=1 \
        -DONNX_GENERATED_SOURCES=$HOME/armnn-devenv/onnx \
        -DBUILD_ONNX_PARSER=1 \
        -DTF_GENERATED_SOURCES=$HOME/armnn-devenv/tensorflow-protobuf \
        -DBUILD_TF_PARSER=1 \
        -DBUILD_TF_LITE_PARSER=1 \
        -DTF_LITE_GENERATED_PATH=$HOME/armnn-devenv/tflite \
        -DFLATBUFFERS_ROOT=$HOME/armnn-devenv/flatbuffers-arm64 \
        -DFLATC_DIR=$HOME/armnn-devenv/flatbuffers-1.12.0/build \
        -DPROTOBUF_ROOT=$HOME/armnn-devenv/google/x86_64_pb_install \
        -DPROTOBUF_ROOT=$HOME/armnn-devenv/google/x86_64_pb_install/ \
        -DPROTOBUF_LIBRARY_DEBUG=$HOME/armnn-devenv/google/arm64_pb_install/lib/libprotobuf.so.23.0.0 \
        -DPROTOBUF_LIBRARY_RELEASE=$HOME/armnn-devenv/google/arm64_pb_install/lib/libprotobuf.so.23.0.0 \
        -DBUILD_ARMNN_QUANTIZER=1 \
        -DBUILD_ARMNN_SERIALIZER=1 \
        -DSAMPLE_DYNAMIC_BACKEND=1 \
        -DDYNAMIC_BACKEND_PATHS=$HOME/armnn-devenv/armnn/src/dynamic/sample/build
```

And these libraries were generated.

```bash
libarmnnBasePipeServer.so
libarmnnBasePipeServer.so.24
libarmnnBasePipeServer.so.24.0
libarmnnOnnxParser.so
libarmnnOnnxParser.so.24
libarmnnOnnxParser.so.24.0
libarmnnQuantizer.so
libarmnnQuantizer.so.24
libarmnnQuantizer.so.24.0
libarmnnSerializer.so
libarmnnSerializer.so.24
libarmnnSerializer.so.24.0
libarmnn.so
libarmnn.so.24
libarmnn.so.24.0
libarmnnTfLiteParser.so
libarmnnTfLiteParser.so.24
libarmnnTfLiteParser.so.24.0
libarmnnTfParser.so
libarmnnTfParser.so.24
libarmnnTfParser.so.24.0
libtimelineDecoderJson.so
libtimelineDecoderJson.so.24
libtimelineDecoderJson.so.24.0
libtimelineDecoder.so
libtimelineDecoder.so.24
libtimelineDecoder.so.24.0
```

But I have problems with building Pyarmnn and use OnnxParser.

1. x86_64 machine: Build pyarmnn together with ArmNN using cmake

    In x86_64 machine, I tried with this cmake options:

```bash
CXX=aarch64-linux-gnu-g++ CC=aarch64-linux-gnu-gcc cmake .. \
        -DCMAKE_C_COMPILER_FLAGS=-fPIC \
        -DARMCOMPUTE_ROOT=$HOME/armnn-devenv/ComputeLibrary \
        -DARMCOMPUTE_BUILD_DIR=$HOME/armnn-devenv/ComputeLibrary/build/ \
        -DBOOST_ROOT=$HOME/armnn-devenv/boost_arm64_install/ \
        -DARMCOMPUTENEON=1 -DARMNNREF=1 \
        -DONNX_GENERATED_SOURCES=$HOME/armnn-devenv/onnx \
        -DBUILD_ONNX_PARSER=1 \
        -DTF_GENERATED_SOURCES=$HOME/armnn-devenv/tensorflow-protobuf \
        -DBUILD_TF_PARSER=1 \
        -DBUILD_TF_LITE_PARSER=1 \
        -DTF_LITE_GENERATED_PATH=$HOME/armnn-devenv/tflite \
        -DFLATBUFFERS_ROOT=$HOME/armnn-devenv/flatbuffers-arm64 \
        -DFLATC_DIR=$HOME/armnn-devenv/flatbuffers-1.12.0/build \
        -DPROTOBUF_ROOT=$HOME/armnn-devenv/google/x86_64_pb_install \
        -DPROTOBUF_ROOT=$HOME/armnn-devenv/google/x86_64_pb_install/ \
        -DPROTOBUF_LIBRARY_DEBUG=$HOME/armnn-devenv/google/arm64_pb_install/lib/libprotobuf.so.23.0.0 \
        -DPROTOBUF_LIBRARY_RELEASE=$HOME/armnn-devenv/google/arm64_pb_install/lib/libprotobuf.so.23.0.0 \
        -DBUILD_ARMNN_QUANTIZER=1 \
        -DBUILD_ARMNN_SERIALIZER=1 \
        -DSAMPLE_DYNAMIC_BACKEND=1 \
        -DDYNAMIC_BACKEND_PATHS=$HOME/armnn-devenv/armnn/src/dynamic/sample/build \
        -DBUILD_PYTHON_SRC=1 \
        -DBUILD_PYTHON_WHL=1 \
        -DSWIG_EXECUTABLE=/usr/local/bin/swig \ #v4.0.2
        -DARMNN_INCLUDE=$HOME/armnn-devenv/armnn/include \
        -DARMNN_LIB=$HOME/armnn-devenv/armnn/build
```

and here's error:

```bash
...
[ 66%] Building CXX object CMakeFiles/ArmnnQuantizerMain.dir/src/armnnQuantizer/ArmNNQuantizerMain.cpp.o
[ 67%] Building CXX object CMakeFiles/armnnTfParser.dir/home/psk/armnn-devenv/tensorflow-protobuf/tensorflow/core/framework/types.pb.cc.o
/opt/conda/compiler_compat/ld: skipping incompatible /home/psk/armnn-devenv/armnn/build/libarmnn.so when searching for -l:libarmnn.so
/opt/conda/compiler_compat/ld: skipping incompatible /home/psk/armnn-devenv/armnn/build/libarmnn.so when searching for -l:libarmnn.so
/opt/conda/compiler_compat/ld: cannot find -l:libarmnn.so
collect2: error: ld returned 1 exit status
error: command 'g++' failed with exit status 1
[ 67%] Building CXX object src/backends/dynamic/reference/CMakeFiles/Arm_CpuRef_backend.dir/__/__/reference/workloads/RefGatherWorkload.cpp.o
python/pyarmnn/CMakeFiles/pyarmnn.dir/build.make:81: recipe for target 'python/pyarmnn/pyarmnn.wrap.timestamp' failed
make[2]: *** [python/pyarmnn/pyarmnn.wrap.timestamp] Error 1
CMakeFiles/Makefile2:2111: recipe for target 'python/pyarmnn/CMakeFiles/pyarmnn.dir/all' failed
make[1]: *** [python/pyarmnn/CMakeFiles/pyarmnn.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
...
```

So I tried to removed pyarmnn related options, re-built, and copied libarmnn.so into `/usr/local/lib` and armnn/include into `/usr/local/include` . And add armnn path to $PATH and \$LD_LIBRARY_PATH. But this gives me the same error messages.

2.  x86_x64 machine: Build ArmNN first and do the standalone build

    I followed this [doc](https://git.mlplatform.org/ml/armnn.git/tree/python/pyarmnn/README.md) and README.md in pyarmnn directories.

    ```bash
    export SWIG_EXECUTABLE=/usr/local/bin/swig
    export ARMNN_INCLUDE=$HOME/armnn-devenv/armnn/include
    export ARMNN_LIB=$HOME/armnn-devenv/armnn/build
    ```

    ```bash
    $ python setup.py clean --all
    running clean
    removing 'build/temp.linux-x86_64-3.8' does not exist -- can't clean it
    removing 'build/lib.linux-x86_64-3.8' does not exist -- can't clean it
    'build/bdist.linux-x86_64' does not exist -- can't clean it
    'build/scripts-3.8' does not exist -- can't clean it
    removing 'build'
    ```

    ```bash
    $ python swig_generate.py -v
    Generating wrap for armnn_version ...
    Generating wrap for armnn ...
    /home/psk/armnn-devenv/armnn/include/armnn/Types.hpp:438: Warning 317: Specialization of non-template 'hash'.
    /home/psk/armnn-devenv/armnn/include/armnn/Types.hpp:448: Warning 317: Specialization of non-template 'hash'.
    /home/psk/armnn-devenv/armnn/include/armnn/Types.hpp:458: Warning 317: Specialization of non-template 'hash'.
    Generating wrap for armnn_caffeparser ...
    Generating wrap for armnn_onnxparser ...
    Generating wrap for armnn_tfparser ...
    Generating wrap for armnn_tfliteparser ...
    Generating wrap for armnn_deserializer ...
    ```

    And I got this error messages:

    ```bash
    $ python setup.py build_ext --inplace
    running build_ext
    building 'pyarmnn._generated._pyarmnn_version' extension
    creating build
    creating build/temp.linux-x86_64-3.8
    creating build/temp.linux-x86_64-3.8/src
    creating build/temp.linux-x86_64-3.8/src/pyarmnn
    creating build/temp.linux-x86_64-3.8/src/pyarmnn/_generated
    gcc -pthread -B /opt/conda/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/psk/armnn-devenv/armnn/include -I/home/psk/armnn-devenv/armnn/include -I/opt/conda/include/python3.8 -c src/pyarmnn/_generated/armnn_version_wrap.cpp -o build/temp.linux-x86_64-3.8/src/pyarmnn/_generated/armnn_version_wrap.o -std=c++14
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    creating build/lib.linux-x86_64-3.8
    creating build/lib.linux-x86_64-3.8/pyarmnn
    creating build/lib.linux-x86_64-3.8/pyarmnn/_generated
    g++ -pthread -shared -B /opt/conda/compiler_compat -L/opt/conda/lib -Wl,-rpath=/opt/conda/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.8/src/pyarmnn/_generated/armnn_version_wrap.o -L/home/psk/armnn-devenv/armnn/build -Wl,-R/home/psk/armnn-devenv/armnn/build -l:libarmnn.so -o build/lib.linux-x86_64-3.8/pyarmnn/_generated/_pyarmnn_version.cpython-38-x86_64-linux-gnu.so
    /opt/conda/compiler_compat/ld: skipping incompatible /home/psk/armnn-devenv/armnn/build/libarmnn.so when searching for -l:libarmnn.so
    /opt/conda/compiler_compat/ld: skipping incompatible /home/psk/armnn-devenv/armnn/build/libarmnn.so when searching for -l:libarmnn.so
    /opt/conda/compiler_compat/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/7/../../../../lib/libarmnn.so when searching for -l:libarmnn.so
    /opt/conda/compiler_compat/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/7/../../../../lib/libarmnn.so when searching for -l:libarmnn.so
    /opt/conda/compiler_compat/ld: skipping incompatible /usr/lib/../lib/libarmnn.so when searching for -l:libarmnn.so
    /opt/conda/compiler_compat/ld: skipping incompatible /usr/lib/../lib/libarmnn.so when searching for -l:libarmnn.so
    /opt/conda/compiler_compat/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/7/../../../libarmnn.so when searching for -l:libarmnn.so
    /opt/conda/compiler_compat/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/7/../../../libarmnn.so when searching for -l:libarmnn.so
    /opt/conda/compiler_compat/ld: skipping incompatible /usr/local/lib/libarmnn.so when searching for -l:libarmnn.so
    /opt/conda/compiler_compat/ld: skipping incompatible /usr/local/lib/libarmnn.so when searching for -l:libarmnn.so
    /opt/conda/compiler_compat/ld: skipping incompatible /usr/lib/libarmnn.so when searching for -l:libarmnn.so
    /opt/conda/compiler_compat/ld: skipping incompatible /usr/lib/libarmnn.so when searching for -l:libarmnn.so
    /opt/conda/compiler_compat/ld: cannot find -l:libarmnn.so
    collect2: error: ld returned 1 exit status
    error: command 'g++' failed with exit status 1
    ```

    

3.  Copy build folder (without any pyarmnn options) from x86 machine to RPI and build Pyarmnn on RPI

    In RPI4, build using script was successful, generating `pyarmnn-24.0.0-cp37-cp37m-linux_aarch64.whl`.

    But it supports only TfLiteParser(), other parsers are not able to use including OnnxParser which I really need.

    ```python
    >>> import pyarmnn as ann
    Your ArmNN library instance does not support Caffe models parser functionality.  Skipped ICaffeParser import.
    Your ArmNN library instance does not support Onnx models parser functionality.  Skipped IOnnxParser import.
    Your ArmNN library instance does not support TF models parser functionality.  Skipped ITfParser import.
    Your ArmNN library instance does not have an armnn models parser funcionality.  Skipped IDeserializer import.
    >>> tfliteparser = ann.ITfLiteParser()
    >>> tfparser = ann.ITfParser()
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/home/pi/.local/lib/python3.7/site-packages/pyarmnn/__init__.py", line 47, in ITfParser
        raise RuntimeError(message)
    RuntimeError: Your ArmNN library instance does not have an armnn models parser funcionality. 
        
    >>> parser = ann.IOnnxParser()
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/home/pi/.local/lib/python3.7/site-packages/pyarmnn/__init__.py", line 34, in IOnnxParser
        raise RuntimeError(message)
    RuntimeError: Your ArmNN library instance does not have an armnn models parser funcionality.
    ```

    Here's my RPI4 info:

    ```bash
    pi@raspberrypi:~ $ lscpu
    Architecture:        aarch64
    Byte Order:          Little Endian
    CPU(s):              4
    On-line CPU(s) list: 0-3
    Thread(s) per core:  1
    Core(s) per socket:  4
    Socket(s):           1
    Vendor ID:           ARM
    Model:               3
    Model name:          Cortex-A72
    Stepping:            r0p3
    CPU max MHz:         1500.0000
    CPU min MHz:         600.0000
    BogoMIPS:            108.00
    Flags:               fp asimd evtstrm crc32 cpuid
    ```

    

Any comments or advices would be appreciated. Thanks.

**Comment by matthewygf** [comment]
@psk9211 hi, originally, I had the same problem where cross compile in a docker armnn provided, and the copy over all the lib* from build directory to the pi4, where onnxparser won't be present. 

all you need to do is also copying the protobuf arm64 files from the "armnn-devenv/google/arm64_pb_install" to your pi4 and install the lib files. :) 

all the best.
<img width="419" alt="onnxparser" src="https://user-images.githubusercontent.com/8476763/119262615-bc810e00-bbd3-11eb-95ab-1c4f54c96a48.PNG">

**Comment by psk9211** [comment]
@matthewygf  Wow it works! I copied all the libraries related to protobuf to RPI4 like you said. So it was the protobuf libraries that causing the problems. Thank you for your advice.

```bash
Python 3.7.3 (default, Jan 22 2021, 20:04:44) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyarmnn as ann
Your ArmNN library instance does not support Caffe models parser functionality.  Skipped ICaffeParser import.
Your ArmNN library instance does not have an armnn models parser funcionality.  Skipped IDeserializer import.
>>> parser = ann.IOnnxParser()
>>> 
```

Unfortunately, all my onnx models are opset >= 12 so I have to convert all over again. I hope they support the latest onnx version soon enough.

Thanks again!

**Comment by matthewygf** [comment]
@keidav01 Although this is solved, I think it is worth updating documentation to avoid this from happening ... Let me know if I can contribute :)
