### ISSUE TITLE
Memory error when running unittest

### ISSUE THREAD

**Issue by photoszzt** [ARM-software/armnn#55]
Has anyone seen this error when running UnitTest: 
```
*** No errors detected
*** Error in `/mnt/data/armnn/build/UnitTests': double free or corruption (!prev): 0x0000aaaaab603a00 ***
```
I put it in gdb to get the stack trace:

```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x0000ffffbabbcdf4 in __GI_abort () at abort.c:89
#2  0x0000ffffbabf4628 in __libc_message (do_abort=do_abort@entry=2, fmt=fmt@entry=0xffffbaca6de0 "*** Error in `%s': %s: 0x%s ***\n") at ../sysdeps/posix/libc_fatal.c:175
#3  0x0000ffffbabfab3c in malloc_printerr (action=3, str=0xffffbaca6eb8 "double free or corruption (!prev)", ptr=<optimized out>, ar_ptr=<optimized out>) at malloc.c:5049
#4  0x0000ffffbabfb458 in _int_free (av=0xffffbaccf998 <main_arena>, p=0xaaaaab6039f0, have_lock=0) at malloc.c:3905
#5  0x0000ffffbe817870 in std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::~pair (this=0xaaaaaae3de30, __in_chrg=<optimized out>) at /usr/include/c++/6/bits/stl_pair.h:194
#6  0x0000ffffbe8305d0 in __gnu_cxx::new_allocator<std::_Rb_tree_node<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >::destroy<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > (this=0xffffbf38f948 <arm_compute::CLKernelLibrary::_program_source_map[abi:cxx11]>, __p=0xaaaaaae3de30) at /usr/include/c++/6/ext/new_allocator.h:124
#7  0x0000ffffbe82fafc in std::allocator_traits<std::allocator<std::_Rb_tree_node<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > >::destroy<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > (__a=..., __p=0xaaaaaae3de30) at /usr/include/c++/6/bits/alloc_traits.h:487
#8  0x0000ffffbe82df40 in std::_Rb_tree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::_Select1st<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >::_M_destroy_node (
    this=0xffffbf38f948 <arm_compute::CLKernelLibrary::_program_source_map[abi:cxx11]>, __p=0xaaaaaae3de10) at /usr/include/c++/6/bits/stl_tree.h:567
#9  0x0000ffffbe82b900 in std::_Rb_tree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::_Select1st<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >::_M_drop_node (
    this=0xffffbf38f948 <arm_compute::CLKernelLibrary::_program_source_map[abi:cxx11]>, __p=0xaaaaaae3de10) at /usr/include/c++/6/bits/stl_tree.h:575
#10 0x0000ffffbe829378 in std::_Rb_tree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::_Select1st<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >::_M_erase (
    this=0xffffbf38f948 <arm_compute::CLKernelLibrary::_program_source_map[abi:cxx11]>, __x=0xaaaaaae3de10) at /usr/include/c++/6/bits/stl_tree.h:1640
#11 0x0000ffffbe826e20 in std::_Rb_tree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::_Select1st<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >::~_Rb_tree (
    this=0xffffbf38f948 <arm_compute::CLKernelLibrary::_program_source_map[abi:cxx11]>, __in_chrg=<optimized out>) at /usr/include/c++/6/bits/stl_tree.h:873
#12 0x0000ffffbe81f53c in std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >::~map (this=0xffffbf38f948 <arm_compute::CLKernelLibrary::_program_source_map[abi:cxx11]>, __in_chrg=<optimized out>)
    at /usr/include/c++/6/bits/stl_map.h:96
#13 0x0000ffffbabbe728 in __cxa_finalize (d=0xffffbe2466a8) at cxa_finalize.c:56
#14 0x0000ffffbd9e5d58 in __do_global_dtors_aux () from /mnt/data/ComputeLibrary/build/libarm_compute_core.so
#15 0x0000ffffbf6e00e4 in _dl_fini () at dl-fini.c:235
#16 0x0000ffffbabbe350 in __run_exit_handlers (status=0, listp=0xffffbaccf4c8 <__exit_funcs>, run_list_atexit=run_list_atexit@entry=true, run_dtors=run_dtors@entry=true) at exit.c:83
#17 0x0000ffffbabbe384 in __GI_exit (status=<optimized out>) at exit.c:105
#18 0x0000ffffbabaa368 in __libc_start_main (main=0x0, argc=0, argv=0x0, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=<optimized out>) at libc-start.c:325
#19 0x0000aaaaaab80670 in _start ()
```
It seems the destructor is called more than once? I'm compiling for caffe.

**Comment by Surmeh** [comment]
Hi @photoszzt,

Could you explain a bit more about your platform, how you compiled ArmNN and Compute Library, and what compilers and standard libraries you are using?

Thanks,
Surabhi

**Comment by photoszzt** [comment]
Hi @Surmeh 

The board is Hikey 960 with Debian. I compile both ArmNN and Compute Library on the board following the instruction posted on github readme. The gcc version is gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516

I compile Compute Library twice to produce a debug and release version. 

Here is my scons invocation:
```bash
scons arch=arm64-v8a extra_cxx_flags="-fPIC" benchmark_tests=1 validation_tests=1 opencl=1 embed_kernels=1 neon=1 debug=1 -j4
```

I compile ArmNN library using the following command:
```
cmake -DARMCOMPUTE_ROOT=../../ComputeLibrary/ -DARMCOMPUTE_BUILD_DIR=../../ComputeLibrary/build -DBOOST_ROOT=/usr/local -DCAFFE_GENERATED_SOURCES=../../caffe/build/src/ -DBUILD_CAFFE_PARSER=1 -DARMCOMPUTENEON=1 -DARMCOMPUTECL=1 -DARMCOMPUTE_CORE_LIBRARY_DEBUG=/mnt/data/ComputeLibrary/build/libarm_compute_core_debug.so -DARMCOMPUTE_CORE_LIBRARY_RELEASE=/mnt/data/ComputeLibrary/build/libarm_compute_core.so -DARMCOMPUTE_INCLUDE=/mnt/data/ComputeLibrary -DARMCOMPUTE_LIBRARY_DEBUG=/mnt/data/ComputeLibrary/build/libarm_compute_debug.so -DARMCOMPUTE_LIBRARY_RELEASE=/mnt/data/ComputeLibrary/build/libarm_compute.so -DOPENCL_INCLUDE=/usr/include -DHALF_INCLUDE=/usr/include ..
```

**Comment by photoszzt** [comment]
The OpenCV version is 3.4.2 which is the most recent one. I use the Boost 1.6.4 as stated in the document.

**Comment by photoszzt** [comment]
@Surmeh Can you reproduce the same problem?

**Comment by Surmeh** [comment]
Hi @photoszzt,

I haven't been able to reproduce the same. Are you following the instructions from https://developer.arm.com/technologies/machine-learning-on-arm/developer-material/how-to-guides/configuring-the-arm-nn-sdk-build-environment-for-caffe?

**Comment by photoszzt** [comment]
Hi @Surmeh 

Yes. I follow this instruction. There're some options that are not included in the instruction. For example, it asks for ARMCOMPUTE_LIBRARY_DEBUG which means I have to compile twice for ArmCompute library. Once to get a debug build and once to get a release build. It also forbits me to specify this library in two directory so I manually copy them to the same directory. These parts are not specify by the documentation but I have to do. I have no idea on whether I do it correctly or not.

**Comment by MatteoArm** [comment]
Hi @photoszzt,

At which point exactly it asks you to set ARMCOMPUTE_LIBRARY_DEBUG? It's a macro that as far as I know we never used. We simply need to set ARMCOMPUTE_BUILD_DIR (like you also did).

Regards
Matteo

**Comment by photoszzt** [comment]
@MatteoArm At the cmake step when building arm nn, I follow the instructions stated in the website and added the -DARMCOMPUTECL=1 flag. Then it asks me that it cannot find the ARMCOMPUTE_LIBRARY_DEBUG.

**Comment by MatteoArm** [comment]
Hi @photoszzt,

When I run the following it doesn't ask for any other macro:

`cmake
      -DCMAKE_BUILD_TYPE=debug
      -DARMCOMPUTE_ROOT=/home/matmar02/devenv/clframework
      -DARMCOMPUTE_BUILD_DIR=/home/matmar02/devenv/clframework/build/aarch64-debug
      -DBOOST_ROOT=/home/matmar02/devenv/install/aarch64/boost
      -DARMCOMPUTENEON=1
      -DARMCOMPUTECL=1
      -DCAFFE_BUILD_ROOT=/home/matmar02/devenv/install/aarch64/caffe
      -DBUILD_CAFFE_PARSER=1
      -DPROTOBUF_ROOT=/home/matmar02/devenv/install/aarch64/protobuf`

I run the above command in my armnn directory (in my case /home/matmar02/devenv/armnn)
Make sure you delete CMakeCache.txt before each new CMake attempt.

Regards
Matteo

**Comment by Surmeh** [comment]
Hi @photoszzt, Were you able to resolve your issue? Please get back in touch if you require any further help.

**Comment by photoszzt** [comment]
@Surmeh Hi Surmeh,

I missed the reply from github. I'm away for a conference now and will test it when I go back.

**Comment by Surmeh** [comment]
Hi @photoszzt, were you able to resolve your issue?

**Comment by Surmeh** [comment]
Thanks, @photoszzt for closing the issue. Please get in touch if you have any more questions.
